### ISSUE TITLE
Investigate what's up with matplotlib-cpp libpython loading on Linux

### ISSUE THREAD

**Issue by mwu-tow** [luna/dataframes#48]
We have this workaround: https://github.com/luna/Dataframes/blob/master/native_libs/third-party/matplotlib-cpp/matplotlibcpp.h#L129

It is abominable. We should investigate to understand why it solves problem on Linux. If possible, it should be removed and fixed in a better. Otherwise, we should at least document it and try making more future proof (what about Pytohn 3.7?).

**Comment by mwu-tow** [comment]
Originally encountered error was as follows:
```
ImportError: /usr/local/lib64/python3.6/site-packages/numpy/core/multiarray.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyExc_UserWarning

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/matplotlib/__init__.py", line 126, in <module>
    from . import cbook
  File "/usr/local/lib64/python3.6/site-packages/matplotlib/cbook/__init__.py", line 34, in <module>
    import numpy as np
  File "/usr/local/lib64/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/lib64/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib64/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib64/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib64/python3.6/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: /usr/local/lib64/python3.6/site-packages/numpy/core/multiarray.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyExc_UserWarning
```

The idea for this workarounds comes from https://bugs.python.org/issue4434
